{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-target-sectigo.fullname" . }}
  labels:
    {{- include "akeyless-target-sectigo.labels" . | nindent 4 }}
data:
  certificate-profile-id: {{ .Values.config.certificate_profile_id | quote }}
  customer-uri: {{ .Values.config.customer_uri | quote }}
  description: {{ .Values.config.description | quote }}
  external-requester: {{ .Values.config.external_requester | quote }}
  key: {{ .Values.config.key | quote }}
  max-versions: {{ .Values.config.max_versions | quote }}
  name: {{ .Values.config.name | quote }}
  organization-id: {{ .Values.config.organization_id | quote }}
  timeout: {{ .Values.config.timeout | quote }}
{{- end }}
