image:
  repository: ghcr.io/pleme-io/placeholder
  tag: latest
  pullPolicy: Always
replicaCount: 1
ports:
- name: http
  containerPort: 8080
  protocol: TCP
service:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
config:
  authentication_credentials: ''
  auto_rotate: ''
  delete_protection: false
  description: ''
  enable_password_policy: ''
  key: ''
  max_versions: ''
  name: ''
  password_length: ''
  rotate_after_disconnect: ''
  rotation_event_in: []
  rotation_hour: 0
  rotation_interval: ''
  tags: []
  target_name: ''
  timeout_sec: 0
  use_capital_letters: ''
  use_lower_letters: ''
  use_numbers: ''
  use_special_characters: ''
secrets:
  custom_payload: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
  alerting:
    enabled: false
  interval: 30s
  port: metrics
  path: /metrics
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
