{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-aws.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-aws.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws-access-key-id: {{ .Values.secrets.aws_access_key_id | quote }}
  aws-access-secret-key: {{ .Values.secrets.aws_access_secret_key | quote }}
{{- end }}
