{{- if .Values.monitoring.alerting.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "akeyless-rotated-secret-ssh.fullname" . }}
  labels:
    {{- include "akeyless-rotated-secret-ssh.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ include "akeyless-rotated-secret-ssh.fullname" . }}.availability
      interval: 30s
      rules:
        - alert: {{ include "akeyless-rotated-secret-ssh.fullname" . | title | replace "-" "" }}Down
          expr: up{{job="{{ include "akeyless-rotated-secret-ssh.fullname" . }}"}} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "{{ include "akeyless-rotated-secret-ssh.fullname" . }} is down"
            description: "{{ include "akeyless-rotated-secret-ssh.fullname" . }} has been down for more than 2 minutes."
{{- end }}
