{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-auth-method-cert.fullname" . }}
  labels:
    {{- include "akeyless-auth-method-cert.labels" . | nindent 4 }}
type: Opaque
stringData:
  certificate-data: {{ .Values.secrets.certificate_data | quote }}
{{- end }}
