{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-target-globalsign-atlas.fullname" . }}
  labels:
    {{- include "akeyless-target-globalsign-atlas.labels" . | nindent 4 }}
data:
  description: {{ .Values.config.description | quote }}
  key: {{ .Values.config.key | quote }}
  max-versions: {{ .Values.config.max_versions | quote }}
  mtls-cert-data-base64: {{ .Values.config.mtls_cert_data_base64 | quote }}
  mtls-key-data-base64: {{ .Values.config.mtls_key_data_base64 | quote }}
  name: {{ .Values.config.name | quote }}
  timeout: {{ .Values.config.timeout | quote }}
{{- end }}
