{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-target-globalsign-atlas.fullname" . }}
  labels:
    {{- include "akeyless-target-globalsign-atlas.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.secrets.api_key | quote }}
  api-secret: {{ .Values.secrets.api_secret | quote }}
{{- end }}
