{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-target-web.fullname" . }}
  labels:
    {{- include "akeyless-target-web.labels" . | nindent 4 }}
data:
  description: {{ .Values.config.description | quote }}
  key: {{ .Values.config.key | quote }}
  max-versions: {{ .Values.config.max_versions | quote }}
  name: {{ .Values.config.name | quote }}
  url: {{ .Values.config.url | quote }}
{{- end }}
