{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-rotated-secret-postgresql.fullname" . }}
  labels:
    {{- include "akeyless-rotated-secret-postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  rotated-password: {{ .Values.secrets.rotated_password | quote }}
{{- end }}
