{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-rdp.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-rdp.labels" . | nindent 4 }}
type: Opaque
stringData:
  rdp-admin-pwd: {{ .Values.secrets.rdp_admin_pwd | quote }}
{{- end }}
