{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-artifactory.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-artifactory.labels" . | nindent 4 }}
type: Opaque
stringData:
  artifactory-admin-pwd: {{ .Values.secrets.artifactory_admin_pwd | quote }}
{{- end }}
