{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-mongodb.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-atlas-api-private-key: {{ .Values.secrets.mongodb_atlas_api_private_key | quote }}
  mongodb-password: {{ .Values.secrets.mongodb_password | quote }}
{{- end }}
