{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-target-gke.fullname" . }}
  labels:
    {{- include "akeyless-target-gke.labels" . | nindent 4 }}
data:
  description: {{ .Values.config.description | quote }}
  gke-cluster-endpoint: {{ .Values.config.gke_cluster_endpoint | quote }}
  gke-cluster-name: {{ .Values.config.gke_cluster_name | quote }}
  gke-service-account-email: {{ .Values.config.gke_service_account_email | quote }}
  key: {{ .Values.config.key | quote }}
  max-versions: {{ .Values.config.max_versions | quote }}
  name: {{ .Values.config.name | quote }}
  use-gw-cloud-identity: {{ .Values.config.use_gw_cloud_identity | quote }}
{{- end }}
