image:
  repository: ghcr.io/pleme-io/placeholder
  tag: latest
  pullPolicy: Always
replicaCount: 1
ports:
- name: http
  containerPort: 8080
  protocol: TCP
service:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
config:
  admin_name: ''
  admin_pwd: ''
  app_private_key_base64: ''
  auth_methods_event_source_locations: []
  auth_type: ''
  client_id: ''
  client_secret: ''
  description: ''
  event_types: []
  every: ''
  gateways_event_source_locations: []
  host: ''
  items_event_source_locations: []
  key: ''
  name: ''
  runner_type: ''
  targets_event_source_locations: []
  user_email: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
  alerting:
    enabled: false
  interval: 30s
  port: metrics
  path: /metrics
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
