{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-target-gemini.fullname" . }}
  labels:
    {{- include "akeyless-target-gemini.labels" . | nindent 4 }}
data:
  api-key: {{ .Values.config.api_key | quote }}
  description: {{ .Values.config.description | quote }}
  gemini-url: {{ .Values.config.gemini_url | quote }}
  key: {{ .Values.config.key | quote }}
  max-versions: {{ .Values.config.max_versions | quote }}
  name: {{ .Values.config.name | quote }}
{{- end }}
