{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-tokenizer.fullname" . }}
  labels:
    {{- include "akeyless-tokenizer.labels" . | nindent 4 }}
data:
  alphabet: {{ .Values.config.alphabet | quote }}
  decoding-template: {{ .Values.config.decoding_template | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  encoding-template: {{ .Values.config.encoding_template | quote }}
  encryption-key-name: {{ .Values.config.encryption_key_name | quote }}
  item-custom-fields: {{ .Values.config.item_custom_fields | quote }}
  name: {{ .Values.config.name | quote }}
  pattern: {{ .Values.config.pattern | quote }}
  tag: {{ .Values.config.tag | quote }}
  template-type: {{ .Values.config.template_type | quote }}
  tokenizer-type: {{ .Values.config.tokenizer_type | quote }}
  tweak-type: {{ .Values.config.tweak_type | quote }}
{{- end }}
