{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-rotated-secret-aws.fullname" . }}
  labels:
    {{- include "akeyless-rotated-secret-aws.labels" . | nindent 4 }}
data:
  api-id: {{ .Values.config.api_id | quote }}
  authentication-credentials: {{ .Values.config.authentication_credentials | quote }}
  auto-rotate: {{ .Values.config.auto_rotate | quote }}
  aws-region: {{ .Values.config.aws_region | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  grace-rotation: {{ .Values.config.grace_rotation | quote }}
  grace-rotation-hour: {{ .Values.config.grace_rotation_hour | quote }}
  grace-rotation-interval: {{ .Values.config.grace_rotation_interval | quote }}
  grace-rotation-timing: {{ .Values.config.grace_rotation_timing | quote }}
  key: {{ .Values.config.key | quote }}
  max-versions: {{ .Values.config.max_versions | quote }}
  name: {{ .Values.config.name | quote }}
  password-length: {{ .Values.config.password_length | quote }}
  rotate-after-disconnect: {{ .Values.config.rotate_after_disconnect | quote }}
  rotation-event-in: {{ .Values.config.rotation_event_in | toJson | quote }}
  rotation-hour: {{ .Values.config.rotation_hour | quote }}
  rotation-interval: {{ .Values.config.rotation_interval | quote }}
  rotator-type: {{ .Values.config.rotator_type | quote }}
  tags: {{ .Values.config.tags | toJson | quote }}
  target-name: {{ .Values.config.target_name | quote }}
{{- end }}
