{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-target-gitlab.fullname" . }}
  labels:
    {{- include "akeyless-target-gitlab.labels" . | nindent 4 }}
type: Opaque
stringData:
  gitlab-access-token: {{ .Values.secrets.gitlab_access_token | quote }}
  gitlab-certificate: {{ .Values.secrets.gitlab_certificate | quote }}
{{- end }}
