image:
  repository: ''
  tag: latest
  pullPolicy: Always
replicaCount: 1
config:
  connection_type: ''
  description: ''
  domain: ''
  hostname: ''
  key: ''
  max_versions: ''
  name: ''
  parent_target_name: ''
  port: ''
  use_tls: false
secrets:
  certificate: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
