{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-target-windows.fullname" . }}
  labels:
    {{- include "akeyless-target-windows.labels" . | nindent 4 }}
type: Opaque
stringData:
  certificate: {{ .Values.secrets.certificate | quote }}
{{- end }}
