{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-auth-method-kerberos.fullname" . }}
  labels:
    {{- include "akeyless-auth-method-kerberos.labels" . | nindent 4 }}
type: Opaque
stringData:
  keytab-file-data: {{ .Values.secrets.keytab_file_data | quote }}
{{- end }}
