{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-dynamic-secret-ldap.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-ldap.labels" . | nindent 4 }}
data:
  ProviderType: {{ .Values.config.ProviderType | quote }}
  bind-dn: {{ .Values.config.bind_dn | quote }}
  custom-username-template: {{ .Values.config.custom_username_template | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  external-username: {{ .Values.config.external_username | quote }}
  fixed-user-claim-keyname: {{ .Values.config.fixed_user_claim_keyname | quote }}
  group-dn: {{ .Values.config.group_dn | quote }}
  host-provider: {{ .Values.config.host_provider | quote }}
  item-custom-fields: {{ .Values.config.item_custom_fields | quote }}
  ldap-ca-cert: {{ .Values.config.ldap_ca_cert | quote }}
  ldap-url: {{ .Values.config.ldap_url | quote }}
  name: {{ .Values.config.name | quote }}
  password-length: {{ .Values.config.password_length | quote }}
  producer-encryption-key-name: {{ .Values.config.producer_encryption_key_name | quote }}
  secure-access-delay: {{ .Values.config.secure_access_delay | quote }}
  secure-access-rd-gateway-server: {{ .Values.config.secure_access_rd_gateway_server | quote }}
  tags: {{ .Values.config.tags | quote }}
  target: {{ .Values.config.target | quote }}
  target-name: {{ .Values.config.target_name | quote }}
  token-expiration: {{ .Values.config.token_expiration | quote }}
  user-attribute: {{ .Values.config.user_attribute | quote }}
  user-dn: {{ .Values.config.user_dn | quote }}
  user-ttl: {{ .Values.config.user_ttl | quote }}
{{- end }}
