{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-ldap.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-ldap.labels" . | nindent 4 }}
type: Opaque
stringData:
  bind-dn-password: {{ .Values.secrets.bind_dn_password | quote }}
{{- end }}
