image:
  repository: ''
  tag: latest
  pullPolicy: Always
replicaCount: 1
config:
  capability: []
  path: ''
  role_name: ''
  rule_type: ''
  ttl: 0
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
