{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-oracle.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-oracle.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-server-certificates: {{ .Values.secrets.db_server_certificates | quote }}
  oracle-password: {{ .Values.secrets.oracle_password | quote }}
{{- end }}
