{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-target-godaddy.fullname" . }}
  labels:
    {{- include "akeyless-target-godaddy.labels" . | nindent 4 }}
data:
  customer-id: {{ .Values.config.customer_id | quote }}
  description: {{ .Values.config.description | quote }}
  imap-fqdn: {{ .Values.config.imap_fqdn | quote }}
  imap-port: {{ .Values.config.imap_port | quote }}
  imap-username: {{ .Values.config.imap_username | quote }}
  key: {{ .Values.config.key | quote }}
  max-versions: {{ .Values.config.max_versions | quote }}
  name: {{ .Values.config.name | quote }}
  timeout: {{ .Values.config.timeout | quote }}
{{- end }}
