image:
  repository: ''
  tag: latest
  pullPolicy: Always
replicaCount: 1
config:
  description: ''
  github_app_id: 0
  github_base_url: ''
  key: ''
  max_versions: ''
  name: ''
secrets:
  github_app_private_key: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
