{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-redshift.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-redshift.labels" . | nindent 4 }}
type: Opaque
stringData:
  redshift-password: {{ .Values.secrets.redshift_password | quote }}
{{- end }}
