image:
  repository: ''
  tag: latest
  pullPolicy: Always
replicaCount: 1
config:
  description: ''
  generate_external_id: false
  key: ''
  max_versions: ''
  name: ''
  region: ''
  role_arn: ''
  use_gw_cloud_identity: false
secrets:
  access_key: ''
  access_key_id: ''
  session_token: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
