image:
  repository: ''
  tag: latest
  pullPolicy: Always
replicaCount: 1
config:
  access_expires: 0
  allowed_client_type: []
  audit_logs_claims: []
  bound_ips: []
  delete_protection: false
  description: ''
  expiration_event_in: []
  force_sub_claims: false
  group_ocid: []
  gw_bound_ips: []
  jwt_ttl: 0
  name: ''
  product_type: []
  tenant_ocid: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
