{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-target-gcp.fullname" . }}
  labels:
    {{- include "akeyless-target-gcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  gcp-key: {{ .Values.secrets.gcp_key | quote }}
{{- end }}
