{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-mysql.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-server-certificates: {{ .Values.secrets.db_server_certificates | quote }}
  mysql-password: {{ .Values.secrets.mysql_password | quote }}
  ssl-certificate: {{ .Values.secrets.ssl_certificate | quote }}
{{- end }}
