{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-dynamic-secret-github.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-github.labels" . | nindent 4 }}
data:
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  github-app-id: {{ .Values.config.github_app_id | quote }}
  github-base-url: {{ .Values.config.github_base_url | quote }}
  installation-id: {{ .Values.config.installation_id | quote }}
  installation-organization: {{ .Values.config.installation_organization | quote }}
  installation-repository: {{ .Values.config.installation_repository | quote }}
  item-custom-fields: {{ .Values.config.item_custom_fields | toJson | quote }}
  name: {{ .Values.config.name | quote }}
  tags: {{ .Values.config.tags | toJson | quote }}
  target-name: {{ .Values.config.target_name | quote }}
  token-permissions: {{ .Values.config.token_permissions | toJson | quote }}
  token-repositories: {{ .Values.config.token_repositories | toJson | quote }}
  token-ttl: {{ .Values.config.token_ttl | quote }}
{{- end }}
