{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-k8s.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  k8s-cluster-ca-cert: {{ .Values.secrets.k8s_cluster_ca_cert | quote }}
  k8s-cluster-token: {{ .Values.secrets.k8s_cluster_token | quote }}
{{- end }}
