{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-static-secret.fullname" . }}
  labels:
    {{- include "akeyless-static-secret.labels" . | nindent 4 }}
type: Opaque
stringData:
  value: {{ .Values.secrets.value | quote }}
{{- end }}
