{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-auth-method-azure-ad.fullname" . }}
  labels:
    {{- include "akeyless-auth-method-azure-ad.labels" . | nindent 4 }}
data:
  access-expires: {{ .Values.config.access_expires | quote }}
  allowed-client-type: {{ .Values.config.allowed_client_type | toJson | quote }}
  audience: {{ .Values.config.audience | quote }}
  audit-logs-claims: {{ .Values.config.audit_logs_claims | toJson | quote }}
  bound-group-id: {{ .Values.config.bound_group_id | toJson | quote }}
  bound-ips: {{ .Values.config.bound_ips | toJson | quote }}
  bound-providers: {{ .Values.config.bound_providers | toJson | quote }}
  bound-resource-id: {{ .Values.config.bound_resource_id | toJson | quote }}
  bound-resource-names: {{ .Values.config.bound_resource_names | toJson | quote }}
  bound-resource-types: {{ .Values.config.bound_resource_types | toJson | quote }}
  bound-rg-id: {{ .Values.config.bound_rg_id | toJson | quote }}
  bound-spid: {{ .Values.config.bound_spid | toJson | quote }}
  bound-sub-id: {{ .Values.config.bound_sub_id | toJson | quote }}
  bound-tenant-id: {{ .Values.config.bound_tenant_id | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  expiration-event-in: {{ .Values.config.expiration_event_in | toJson | quote }}
  force-sub-claims: {{ .Values.config.force_sub_claims | quote }}
  gw-bound-ips: {{ .Values.config.gw_bound_ips | toJson | quote }}
  issuer: {{ .Values.config.issuer | quote }}
  jwks-uri: {{ .Values.config.jwks_uri | quote }}
  jwt-ttl: {{ .Values.config.jwt_ttl | quote }}
  name: {{ .Values.config.name | quote }}
  product-type: {{ .Values.config.product_type | toJson | quote }}
  unique-identifier: {{ .Values.config.unique_identifier | quote }}
{{- end }}
