{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-cassandra.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-cassandra.labels" . | nindent 4 }}
type: Opaque
stringData:
  cassandra-password: {{ .Values.secrets.cassandra_password | quote }}
  ssl-certificate: {{ .Values.secrets.ssl_certificate | quote }}
{{- end }}
