{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-target-aws.fullname" . }}
  labels:
    {{- include "akeyless-target-aws.labels" . | nindent 4 }}
data:
  description: {{ .Values.config.description | quote }}
  generate-external-id: {{ .Values.config.generate_external_id | quote }}
  key: {{ .Values.config.key | quote }}
  max-versions: {{ .Values.config.max_versions | quote }}
  name: {{ .Values.config.name | quote }}
  region: {{ .Values.config.region | quote }}
  role-arn: {{ .Values.config.role_arn | quote }}
  use-gw-cloud-identity: {{ .Values.config.use_gw_cloud_identity | quote }}
{{- end }}
