{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-role-rule.fullname" . }}
  labels:
    {{- include "akeyless-role-rule.labels" . | nindent 4 }}
data:
  capability: {{ .Values.config.capability | toJson | quote }}
  path: {{ .Values.config.path | quote }}
  role-name: {{ .Values.config.role_name | quote }}
  rule-type: {{ .Values.config.rule_type | quote }}
  ttl: {{ .Values.config.ttl | quote }}
{{- end }}
