{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-target-zerossl.fullname" . }}
  labels:
    {{- include "akeyless-target-zerossl.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.secrets.api_key | quote }}
  imap-password: {{ .Values.secrets.imap_password | quote }}
{{- end }}
