image:
  repository: ''
  tag: latest
  pullPolicy: Always
replicaCount: 1
config:
  creation_statements: ''
  custom_username_template: ''
  delete_protection: false
  description: ''
  item_custom_fields: {}
  name: ''
  password_length: ''
  producer_encryption_key: ''
  redshift_db_name: ''
  redshift_host: ''
  redshift_port: ''
  redshift_username: ''
  ssl: false
  tags: []
  target_name: ''
  user_ttl: ''
secrets:
  redshift_password: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
