{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-auth-method-k8s.fullname" . }}
  labels:
    {{- include "akeyless-auth-method-k8s.labels" . | nindent 4 }}
data:
  access-expires: {{ .Values.config.access_expires | quote }}
  allowed-client-type: {{ .Values.config.allowed_client_type | quote }}
  audience: {{ .Values.config.audience | quote }}
  audit-logs-claims: {{ .Values.config.audit_logs_claims | quote }}
  bound-ips: {{ .Values.config.bound_ips | quote }}
  bound-namespaces: {{ .Values.config.bound_namespaces | quote }}
  bound-pod-names: {{ .Values.config.bound_pod_names | quote }}
  bound-sa-names: {{ .Values.config.bound_sa_names | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  expiration-event-in: {{ .Values.config.expiration_event_in | quote }}
  force-sub-claims: {{ .Values.config.force_sub_claims | quote }}
  gen-key: {{ .Values.config.gen_key | quote }}
  gw-bound-ips: {{ .Values.config.gw_bound_ips | quote }}
  jwt-ttl: {{ .Values.config.jwt_ttl | quote }}
  name: {{ .Values.config.name | quote }}
  product-type: {{ .Values.config.product_type | quote }}
  public-key: {{ .Values.config.public_key | quote }}
{{- end }}
