apiVersion: v2
name: akeyless-auth-method-aws-iam
description: Manages an AWS IAM authentication method
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
- name: pleme-lib
  version: ~0.4.0
  repository: file://../pleme-lib
annotations:
  pleme.io/category: auth_method
  pleme.io/generated: 'true'
  pleme.io/provider: akeyless
