{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-ping.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-ping.labels" . | nindent 4 }}
type: Opaque
stringData:
  ping-password: {{ .Values.secrets.ping_password | quote }}
{{- end }}
