{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-rotated-secret-ldap.fullname" . }}
  labels:
    {{- include "akeyless-rotated-secret-ldap.labels" . | nindent 4 }}
data:
  ProviderType: {{ .Values.config.ProviderType | quote }}
  authentication-credentials: {{ .Values.config.authentication_credentials | quote }}
  auto-rotate: {{ .Values.config.auto_rotate | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  host-provider: {{ .Values.config.host_provider | quote }}
  key: {{ .Values.config.key | quote }}
  max-versions: {{ .Values.config.max_versions | quote }}
  name: {{ .Values.config.name | quote }}
  password-length: {{ .Values.config.password_length | quote }}
  rotate-after-disconnect: {{ .Values.config.rotate_after_disconnect | quote }}
  rotated-username: {{ .Values.config.rotated_username | quote }}
  rotation-event-in: {{ .Values.config.rotation_event_in | quote }}
  rotation-hour: {{ .Values.config.rotation_hour | quote }}
  rotation-interval: {{ .Values.config.rotation_interval | quote }}
  rotator-type: {{ .Values.config.rotator_type | quote }}
  tags: {{ .Values.config.tags | quote }}
  target: {{ .Values.config.target | quote }}
  target-name: {{ .Values.config.target_name | quote }}
  user-attribute: {{ .Values.config.user_attribute | quote }}
  user-dn: {{ .Values.config.user_dn | quote }}
{{- end }}
