{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-dynamic-secret-gcp.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-gcp.labels" . | nindent 4 }}
data:
  access-type: {{ .Values.config.access_type | quote }}
  custom-username-template: {{ .Values.config.custom_username_template | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  fixed-user-claim-keyname: {{ .Values.config.fixed_user_claim_keyname | quote }}
  gcp-cred-type: {{ .Values.config.gcp_cred_type | quote }}
  gcp-key: {{ .Values.config.gcp_key | quote }}
  gcp-key-algo: {{ .Values.config.gcp_key_algo | quote }}
  gcp-project-id: {{ .Values.config.gcp_project_id | quote }}
  gcp-sa-email: {{ .Values.config.gcp_sa_email | quote }}
  gcp-token-scopes: {{ .Values.config.gcp_token_scopes | quote }}
  item-custom-fields: {{ .Values.config.item_custom_fields | quote }}
  name: {{ .Values.config.name | quote }}
  producer-encryption-key-name: {{ .Values.config.producer_encryption_key_name | quote }}
  role-binding: {{ .Values.config.role_binding | quote }}
  role-names: {{ .Values.config.role_names | quote }}
  secure-access-delay: {{ .Values.config.secure_access_delay | quote }}
  service-account-type: {{ .Values.config.service_account_type | quote }}
  tags: {{ .Values.config.tags | quote }}
  target-name: {{ .Values.config.target_name | quote }}
  user-ttl: {{ .Values.config.user_ttl | quote }}
{{- end }}
