image:
  repository: ''
  tag: latest
  pullPolicy: Always
replicaCount: 1
config:
  description: ''
  k8s_auth_type: ''
  k8s_cluster_endpoint: ''
  k8s_cluster_name: ''
  key: ''
  max_versions: ''
  name: ''
  use_gw_service_account: false
secrets:
  k8s_client_certificate: ''
  k8s_client_key: ''
  k8s_cluster_ca_cert: ''
  k8s_cluster_token: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
