image:
  repository: ghcr.io/pleme-io/placeholder
  tag: latest
  pullPolicy: Always
replicaCount: 1
ports:
- name: http
  containerPort: 8080
  protocol: TCP
service:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
config:
  description: ''
  k8s_auth_type: ''
  k8s_cluster_endpoint: ''
  k8s_cluster_name: ''
  key: ''
  max_versions: ''
  name: ''
  use_gw_service_account: false
secrets:
  k8s_client_certificate: ''
  k8s_client_key: ''
  k8s_cluster_ca_cert: ''
  k8s_cluster_token: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
  alerting:
    enabled: false
  interval: 30s
  port: metrics
  path: /metrics
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
