image:
  repository: ghcr.io/pleme-io/placeholder
  tag: latest
  pullPolicy: Always
replicaCount: 1
ports:
- name: http
  containerPort: 8080
  protocol: TCP
service:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
config:
  admin_rotation_interval_days: 0
  create_sync_url: ''
  delete_protection: false
  description: ''
  enable_admin_rotation: false
  item_custom_fields: {}
  name: ''
  payload: ''
  producer_encryption_key_name: ''
  revoke_sync_url: ''
  rotate_sync_url: ''
  tags: []
  timeout_sec: 0
  user_ttl: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
  alerting:
    enabled: false
  interval: 30s
  port: metrics
  path: /metrics
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
