{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-postgresql.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.secrets.postgresql_password | quote }}
{{- end }}
