{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-auth-method-gcp.fullname" . }}
  labels:
    {{- include "akeyless-auth-method-gcp.labels" . | nindent 4 }}
data:
  access-expires: {{ .Values.config.access_expires | quote }}
  allowed-client-type: {{ .Values.config.allowed_client_type | quote }}
  audience: {{ .Values.config.audience | quote }}
  audit-logs-claims: {{ .Values.config.audit_logs_claims | quote }}
  bound-ips: {{ .Values.config.bound_ips | quote }}
  bound-labels: {{ .Values.config.bound_labels | quote }}
  bound-projects: {{ .Values.config.bound_projects | quote }}
  bound-regions: {{ .Values.config.bound_regions | quote }}
  bound-service-accounts: {{ .Values.config.bound_service_accounts | quote }}
  bound-zones: {{ .Values.config.bound_zones | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  expiration-event-in: {{ .Values.config.expiration_event_in | quote }}
  force-sub-claims: {{ .Values.config.force_sub_claims | quote }}
  gw-bound-ips: {{ .Values.config.gw_bound_ips | quote }}
  jwt-ttl: {{ .Values.config.jwt_ttl | quote }}
  name: {{ .Values.config.name | quote }}
  product-type: {{ .Values.config.product_type | quote }}
  type: {{ .Values.config.type | quote }}
  unique-identifier: {{ .Values.config.unique_identifier | quote }}
{{- end }}
