image:
  repository: ''
  tag: latest
  pullPolicy: Always
replicaCount: 1
config:
  authentication_credentials: ''
  auto_rotate: ''
  delete_protection: false
  description: ''
  gcp_key: ''
  gcp_service_account_email: ''
  gcp_service_account_key_id: ''
  grace_rotation: ''
  grace_rotation_hour: 0
  grace_rotation_interval: ''
  grace_rotation_timing: ''
  key: ''
  max_versions: ''
  name: ''
  password_length: ''
  rotation_event_in: []
  rotation_hour: 0
  rotation_interval: ''
  rotator_type: ''
  tags: []
  target_name: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
