{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-dockerhub.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-dockerhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  dockerhub-password: {{ .Values.secrets.dockerhub_password | quote }}
{{- end }}
