image:
  repository: ''
  tag: latest
  pullPolicy: Always
replicaCount: 1
config:
  alphabet: ''
  decoding_template: ''
  delete_protection: ''
  description: ''
  encoding_template: ''
  encryption_key_name: ''
  item_custom_fields: {}
  name: ''
  pattern: ''
  tag: []
  template_type: ''
  tokenizer_type: ''
  tweak_type: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
