image:
  repository: ''
  tag: latest
  pullPolicy: Always
replicaCount: 1
config:
  activate_keys_on_creation: ''
  certificate_ttl: 0
  name: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
