image:
  repository: ghcr.io/pleme-io/placeholder
  tag: latest
  pullPolicy: Always
replicaCount: 1
ports:
- name: http
  containerPort: 8080
  protocol: TCP
service:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
config:
  activate_keys_on_creation: ''
  certificate_ttl: 0
  name: ''
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
monitoring:
  enabled: true
  alerting:
    enabled: false
  interval: 30s
  port: metrics
  path: /metrics
networkPolicy:
  enabled: true
pdb:
  enabled: false
autoscaling:
  enabled: false
