{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-target-rabbitmq.fullname" . }}
  labels:
    {{- include "akeyless-target-rabbitmq.labels" . | nindent 4 }}
type: Opaque
stringData:
  rabbitmq-server-password: {{ .Values.secrets.rabbitmq_server_password | quote }}
{{- end }}
