{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-auth-method-oauth2.fullname" . }}
  labels:
    {{- include "akeyless-auth-method-oauth2.labels" . | nindent 4 }}
data:
  access-expires: {{ .Values.config.access_expires | quote }}
  allowed-client-type: {{ .Values.config.allowed_client_type | toJson | quote }}
  audience: {{ .Values.config.audience | quote }}
  audit-logs-claims: {{ .Values.config.audit_logs_claims | toJson | quote }}
  bound-client-ids: {{ .Values.config.bound_client_ids | toJson | quote }}
  bound-ips: {{ .Values.config.bound_ips | toJson | quote }}
  cert: {{ .Values.config.cert | quote }}
  cert-file-data: {{ .Values.config.cert_file_data | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  expiration-event-in: {{ .Values.config.expiration_event_in | toJson | quote }}
  force-sub-claims: {{ .Values.config.force_sub_claims | quote }}
  gateway-url: {{ .Values.config.gateway_url | quote }}
  gw-bound-ips: {{ .Values.config.gw_bound_ips | toJson | quote }}
  issuer: {{ .Values.config.issuer | quote }}
  jwks-json-data: {{ .Values.config.jwks_json_data | quote }}
  jwks-uri: {{ .Values.config.jwks_uri | quote }}
  jwt-ttl: {{ .Values.config.jwt_ttl | quote }}
  name: {{ .Values.config.name | quote }}
  product-type: {{ .Values.config.product_type | toJson | quote }}
  subclaims-delimiters: {{ .Values.config.subclaims_delimiters | toJson | quote }}
  unique-identifier: {{ .Values.config.unique_identifier | quote }}
{{- end }}
