{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-certificate.fullname" . }}
  labels:
    {{- include "akeyless-certificate.labels" . | nindent 4 }}
data:
  certificate-data: {{ .Values.config.certificate_data | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  expiration-event-in: {{ .Values.config.expiration_event_in | quote }}
  format: {{ .Values.config.format | quote }}
  item-custom-fields: {{ .Values.config.item_custom_fields | quote }}
  key: {{ .Values.config.key | quote }}
  key-data: {{ .Values.config.key_data | quote }}
  name: {{ .Values.config.name | quote }}
  tags: {{ .Values.config.tags | quote }}
{{- end }}
