{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-azure.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-azure.labels" . | nindent 4 }}
type: Opaque
stringData:
  azure-client-secret: {{ .Values.secrets.azure_client_secret | quote }}
{{- end }}
