{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-dynamic-secret-openai.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-openai.labels" . | nindent 4 }}
data:
  custom-username-template: {{ .Values.config.custom_username_template | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  item-custom-fields: {{ .Values.config.item_custom_fields | toJson | quote }}
  name: {{ .Values.config.name | quote }}
  producer-encryption-key-name: {{ .Values.config.producer_encryption_key_name | quote }}
  project-id: {{ .Values.config.project_id | quote }}
  tags: {{ .Values.config.tags | toJson | quote }}
  target-name: {{ .Values.config.target_name | quote }}
  user-ttl: {{ .Values.config.user_ttl | quote }}
{{- end }}
