{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-auth-method-aws-iam.fullname" . }}
  labels:
    {{- include "akeyless-auth-method-aws-iam.labels" . | nindent 4 }}
data:
  access-expires: {{ .Values.config.access_expires | quote }}
  allowed-client-type: {{ .Values.config.allowed_client_type | quote }}
  audit-logs-claims: {{ .Values.config.audit_logs_claims | quote }}
  bound-arn: {{ .Values.config.bound_arn | quote }}
  bound-aws-account-id: {{ .Values.config.bound_aws_account_id | quote }}
  bound-ips: {{ .Values.config.bound_ips | quote }}
  bound-resource-id: {{ .Values.config.bound_resource_id | quote }}
  bound-role-id: {{ .Values.config.bound_role_id | quote }}
  bound-role-name: {{ .Values.config.bound_role_name | quote }}
  bound-user-id: {{ .Values.config.bound_user_id | quote }}
  bound-user-name: {{ .Values.config.bound_user_name | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  description: {{ .Values.config.description | quote }}
  expiration-event-in: {{ .Values.config.expiration_event_in | quote }}
  force-sub-claims: {{ .Values.config.force_sub_claims | quote }}
  gw-bound-ips: {{ .Values.config.gw_bound_ips | quote }}
  jwt-ttl: {{ .Values.config.jwt_ttl | quote }}
  name: {{ .Values.config.name | quote }}
  product-type: {{ .Values.config.product_type | quote }}
  sts-url: {{ .Values.config.sts_url | quote }}
  unique-identifier: {{ .Values.config.unique_identifier | quote }}
{{- end }}
