{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akeyless-auth-method-universal-identity.fullname" . }}
  labels:
    {{- include "akeyless-auth-method-universal-identity.labels" . | nindent 4 }}
data:
  access-expires: {{ .Values.config.access_expires | quote }}
  allowed-client-type: {{ .Values.config.allowed_client_type | toJson | quote }}
  audit-logs-claims: {{ .Values.config.audit_logs_claims | toJson | quote }}
  bound-ips: {{ .Values.config.bound_ips | toJson | quote }}
  delete-protection: {{ .Values.config.delete_protection | quote }}
  deny-inheritance: {{ .Values.config.deny_inheritance | quote }}
  deny-rotate: {{ .Values.config.deny_rotate | quote }}
  description: {{ .Values.config.description | quote }}
  expiration-event-in: {{ .Values.config.expiration_event_in | toJson | quote }}
  force-sub-claims: {{ .Values.config.force_sub_claims | quote }}
  gw-bound-ips: {{ .Values.config.gw_bound_ips | toJson | quote }}
  jwt-ttl: {{ .Values.config.jwt_ttl | quote }}
  name: {{ .Values.config.name | quote }}
  product-type: {{ .Values.config.product_type | toJson | quote }}
  ttl: {{ .Values.config.ttl | quote }}
{{- end }}
