{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-eks.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-eks.labels" . | nindent 4 }}
type: Opaque
stringData:
  eks-access-key-id: {{ .Values.secrets.eks_access_key_id | quote }}
  eks-cluster-ca-cert: {{ .Values.secrets.eks_cluster_ca_cert | quote }}
  eks-secret-access-key: {{ .Values.secrets.eks_secret_access_key | quote }}
{{- end }}
