{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeyless-dynamic-secret-gke.fullname" . }}
  labels:
    {{- include "akeyless-dynamic-secret-gke.labels" . | nindent 4 }}
type: Opaque
stringData:
  gke-account-key: {{ .Values.secrets.gke_account_key | quote }}
  gke-cluster-cert: {{ .Values.secrets.gke_cluster_cert | quote }}
{{- end }}
